# Generated by Django 5.1.2 on 2025-01-22 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0002_alter_profesor_fecha_contratacion'),
        ('secciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='profesores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesores.profesor'),
        ),
    ]
