# Generated by Django 5.1.2 on 2025-01-22 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0004_remove_curso_profesores'),
        ('profesores', '0002_alter_profesor_fecha_contratacion'),
        ('secciones', '0002_seccion_profesores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='profesores',
        ),
        migrations.AddField(
            model_name='seccion',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profesores.profesor'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cursos.curso'),
        ),
    ]
