# Generated by Django 5.1.2 on 2025-01-14 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_alter_curso_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
