# Generated by Django 5.1.2 on 2024-12-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_alter_estudiante_anio_escolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='anio_escolar',
            field=models.CharField(max_length=10),
        ),
    ]
