# Generated by Django 5.1.2 on 2024-12-20 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anio_escolar', '0001_initial'),
        ('estudiantes', '0004_alter_estudiante_anio_escolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='anio_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anio_escolar.anioescolar', verbose_name='Año Escolar'),
        ),
    ]
