# Generated by Django 5.1.2 on 2025-01-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_alter_estudiante_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Aplleidos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
    ]
