# Generated by Django 5.1.2 on 2025-01-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_registration_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='curso_a_solicitar',
            field=models.CharField(choices=[('HSC', 'Habilidades Sociales y Comunicación'), ('DLC', 'Desarrollo del Lenguaje y la Comunicación'), ('ECA', 'Estimulación Cognitiva y Aprendizaje'), ('HVD', 'Habilidades para la Vida Diaria'), ('TA', 'Tecnología Asistiva'), ('EAC', 'Expresión Artística y Creatividad'), ('PEE', 'Preparación para la Inclusión Escolar'), ('IBA', 'Informática Básica Adaptada'), ('EMC', 'Estrategias de Manejo Conductual'), ('CE', 'Comunicación Efectiva con Niños con Necesidades Especiales'), ('AC', 'Adaptaciones Curriculares'), ('IT', 'Intervención Temprana'), ('CNE', 'Conociendo las Necesidades Educativas Especiales')], default='HSC', max_length=3, verbose_name='Curso a Solicitar'),
        ),
    ]
