# Generated by Django 5.1.2 on 2025-01-14 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='fecha_contratacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
